name: Reusable workflow example

on:
  workflow_call:
    inputs:
      dept:
        type: string
        default: true
    secrets:
      city:
        required: true
    outputs:
      output-top-1:
        description: "The last output string"
        value: ${{ jobs.reuse1job.outputs.output1 }}

jobs:
  reuse1job:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test != 'success' && 'yes1' || 'no1' }}
    steps:
        
    - id: step1
      run: echo "test=success" >> $GITHUB_OUTPUT

    - name: List Files 2
      run: |
        echo dept is ${{inputs.dept}}
        echo city secret is ${{secrets.city}}
    
