name: Reusable workflow example

on:
  workflow_call:
    inputs:
      someinput:
        type: string

jobs:
  reuse2job:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Greet 1
      id: greet1
      run: |
        echo "Hi 1"
    - name: Greet 2
      id: greet2
      run: |
        echo "Hi 2"
    - name: Greet 3
      id: greet3
      run: |
        echo ${{ inputs.someinput }}
