name: Call a reusable workflows.

on:
  workflow_call:

jobs:
  reuse0:
    uses: allthings-dev/github-actions-reusable-workflows/.github/workflows/reusable-workflow-1.yml@main

  reusemid:
    runs-on: ubuntu-latest
    needs: reuse0
    steps:
      - run: echo " reuse0 status is " ${{ needs.reuse0.result }}

  reuse1:
    uses: allthings-dev/github-actions-reusable-workflows/.github/workflows/reusable-workflow-1.yml@main
    needs: [reuse0]
    #if: ${{ needs.reuse0.outputs.lastgreet != 'hello' }}
    if: ${{ needs.reuse0.result == 'success' }}
    
  reuse2:
    uses: allthings-dev/github-actions-reusable-workflows/.github/workflows/reusable-workflow-2.yml@main
    needs: [reuse0]
    #if: ${{ needs.reuse1.outputs.lastgreet != 'hello' }}
    if: ${{ needs.reuse0.result == 'failure' }}
  
  reuse3:
    uses: allthings-dev/github-actions-reusable-workflows/.github/workflows/reusable-workflow-1.yml@main
    needs: [ reuse1, reuse2 ]
    if: ${{ !cancelled() && (needs.reuse1.result == 'success' || needs.reuse2.result == 'success') }}
      

  reuse4:
    uses: allthings-dev/github-actions-reusable-workflows/.github/workflows/reusable-workflow-1.yml@main
    needs: [reuse3 ]
    if: ${{ !cancelled() && needs.reuse3.result == 'success' }}

  reuse5:
    uses: allthings-dev/github-actions-reusable-workflows/.github/workflows/reusable-workflow-1.yml@main
    needs: [reuse4]
    if: ${{ !cancelled() && needs.reuse4.result == 'success' }}
    
