name: Reusable workflow example

on:
  workflow_call:

jobs:
  reuse1job:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4
    - name: List Files 1
      run: |
        pwd
        ls -l
        echo "done"
        efr
    - name: List Files 2
      if: always()
      run: |
        pwd
        ls -l
        echo "done"
    
