name: Call a reusable workflows.

on:
  workflow_call:

jobs:
  reuse1:
    uses: allthings-dev/github-actions-reusable-workflows/.github/workflows/reusable-workflow-1.yml@main

  reuse2:
    uses: allthings-dev/github-actions-reusable-workflows/.github/workflows/reusable-workflow-2.yml@main
    needs: [reuse1]
    #if: ${{ needs.reuse1.outputs.lastgreet != 'hello' }}
    if: false
  
  reuse3:
    uses: allthings-dev/github-actions-reusable-workflows/.github/workflows/reusable-workflow-1.yml@main
    needs: [ reuse1, reuse2 ]
    if: |
      always() && (needs.reuse1.result == 'success' || needs.reuse2.result == 'success')

  reuse4:
    uses: allthings-dev/github-actions-reusable-workflows/.github/workflows/reusable-workflow-1.yml@main
    needs: [reuse3 ]
    if: success()

  reuse5:
    uses: allthings-dev/github-actions-reusable-workflows/.github/workflows/reusable-workflow-1.yml@main
    needs: [reuse4]
    
