name: Reusable workflow example

on:
  workflow_call:
    inputs:
      donotfail:
        type: boolean
        default: true
    outputs:
      lastgreet:
        description: "The last output string"
        value: ${{ jobs.reuse1job.outputs.output1 }}

jobs:
  reuse1job:
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      output1: ${{ steps.step1.outputs.firstgreet }}
    steps:
    - uses: actions/checkout@v4
    - name: List Files 1
      run: |
        pwd
        ls -l
        echo "done"
    - name: Fail on error
      run: |
        echo "donex"
        cjkrjc
        
    - id: step1
      run: echo "firstgreet=hello" >> $GITHUB_OUTPUT

    - name: List Files 2
      if: always()
      run: |
        pwd
        ls -l
        echo "done"
    
